"""empty message

Revision ID: 02b97024942c
Revises: 3ae8a59a99b9
Create Date: 2025-01-30 15:13:39.530612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b97024942c'
down_revision = '3ae8a59a99b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.drop_column('event_date')

    # ### end Alembic commands ###
