"""empty message

Revision ID: 1c5b910afd08
Revises: d0d36b2970df
Create Date: 2025-04-03 02:51:58.565175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5b910afd08'
down_revision = 'd0d36b2970df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_duration', sa.Integer(), nullable=True))
        batch_op.alter_column('question_bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Exams', schema=None) as batch_op:
        batch_op.alter_column('question_bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('exam_duration')

    # ### end Alembic commands ###
