"""empty message

Revision ID: 1ecd85d09b46
Revises: 670af086757b
Create Date: 2024-12-18 02:29:37.019367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecd85d09b46'
down_revision = '670af086757b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Questions', schema=None) as batch_op:
        batch_op.drop_column('correct_answer')

    # ### end Alembic commands ###
