"""empty message

Revision ID: 2c36d0cdbc52
Revises: 6b50e54eb146
Create Date: 2025-04-06 05:39:00.582316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c36d0cdbc52'
down_revision = '6b50e54eb146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Results', schema=None) as batch_op:
        batch_op.drop_constraint('Results_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Results_student_id_fkey', 'Student_Details', ['student_id'], ['id'])

    # ### end Alembic commands ###
