"""empty message

Revision ID: 3ae8a59a99b9
Revises: b25977e28733
Create Date: 2025-01-30 13:07:44.220722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae8a59a99b9'
down_revision = 'b25977e28733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('departments', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('semesters', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('courses', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.drop_column('courses')
        batch_op.drop_column('semesters')
        batch_op.drop_column('departments')
        batch_op.drop_column('years')

    # ### end Alembic commands ###
