"""empty message

Revision ID: c0dbcf93776a
Revises: df7bbf62c7bf
Create Date: 2025-04-06 02:28:41.474767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0dbcf93776a'
down_revision = 'df7bbf62c7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_answer', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=1), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('correct_answers',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.alter_column('correct_answers',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_questions',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('selected_answer')

    # ### end Alembic commands ###
