"""empty message

Revision ID: d0d36b2970df
Revises: 9270a9b4f738
Create Date: 2025-04-03 01:16:50.859922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0d36b2970df'
down_revision = '9270a9b4f738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('question_bank_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Events.id'], ),
    sa.ForeignKeyConstraint(['question_bank_id'], ['Question_Banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    op.drop_table('Exams')
    # ### end Alembic commands ###
