"""empty message

Revision ID: d2c732d8cc0c
Revises: c0dbcf93776a
Create Date: 2025-04-06 04:34:02.869768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2c732d8cc0c'
down_revision = 'c0dbcf93776a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('selected_answer', sa.String(length=1), nullable=False),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='result_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='result_pkey')
    )
    op.drop_table('Results')
    # ### end Alembic commands ###
