"""empty message

Revision ID: fda8265e3b42
Revises: 8fb5c4d572c1
Create Date: 2025-04-05 17:32:31.949631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda8265e3b42'
down_revision = '8fb5c4d572c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('Events', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'end_time')
    op.drop_column('Events', 'start_time')
    # ### end Alembic commands ###
